# Generated by Django 3.2.4 on 2021-06-19 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20210619_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.tasktype'),
        ),
        migrations.AlterField(
            model_name='tasktype',
            name='name',
            field=models.CharField(help_text='Enter a task type ', max_length=30),
        ),
    ]
