# Generated by Django 3.2.4 on 2021-06-19 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20210619_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='more_discript',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
