# Generated by Django 3.2.4 on 2021-06-20 04:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0004_event_more_discript'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='more_discript',
        ),
        migrations.CreateModel(
            name='TakenEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AcceptanceTime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('performer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
