# Generated by Django 3.2.4 on 2021-06-21 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20210621_1138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'permissions': (('create_event', 'Able to create new event'),)},
        ),
    ]
