# Generated by Django 3.2.4 on 2021-06-24 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_event_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='takenevent',
            name='response_file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
